formpreview_test/urls.py
"""formpreview_test URL Configuration

"""
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^post_games', include('games.urls')),
    url(r'^view_games/', include('view_games.urls')),
)

games/urls.py
import views

from django.conf.urls import patterns, url
from games.preview import GameFormPreview
from games.forms import GameForm
from django import forms

urlpatterns = patterns('',
  url(r'^$', GameFormPreview(GameForm)),
  url(r'^/submit$', views.form_upload, name='form_upload'),
)

view_games/urls.py
import views

from django.conf.urls import patterns, url

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
  url(r'^game/(?P<game_id>\d+)/$', views.game, name='game'),
)

games/models.py
# models.py
from django.db import models
from django import forms

class Game(models.Model):

  # Game Choices
  FOOTBALL = 0
  BASKETBALL = 1
  TENNIS = 2
  OTHER = 3
  GAME_CHOICES = (
      (FOOTBALL, 'Football'),
      (BASKETBALL, 'Basketball'),
      (TENNIS, 'Tennis'),
      (OTHER, 'Other')
    )

  game_id = models.AutoField(primary_key=True)
  location = models.CharField(max_length=200, verbose_name="Location")
  game = models.IntegerField(choices=GAME_CHOICES, default=FOOTBALL)
  game_date = models.DateField(verbose_name='Game Date')

view_games/models.py
from django.db import models

# Create your models here.

games/forms.py
# forms.py
from django import forms
from django.forms import ModelForm 
from .models import Game

class GameForm(ModelForm):
  class Meta:
    model = Game
    fields = (
      'location',
      'game',
      'game_date'
    )

games/views.py
from django.shortcuts import render
from .models import Game
from .forms import GameForm

def form_upload(request):
  if request.method == 'GET':
    form = GameForm()
  else:
    # A POST request: Handle Form Upload
    form = GameForm(request.POST) # Bind data from request.POST into a GameForm
    # If data is valid, proceeds to create a new game and redirect the user
    if form.is_valid():
      game = form.save()
      return render(request, 'games/success.html', {})
  return render(request, 'games/form_upload.html', {
    'form': form,
  })

view_games/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse

from games.models import Game
 
def index(request):
  game_list = Game.objects.order_by('game_id').values_list('game_id', flat=True).distinct()
  context = {'game_list': game_list}
  return render(request, 'view_games/index.html', context)

def game(request, game_id):
  game = Game.objects.filter(game_id=game_id).distinct()[0]
  context = {'game': game}
  return render(request, 'view_games/game.html', context)

games/templates/games/form_upload.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>form_upload</title>
  </head>
  <body>

    <form method="post">
      {% csrf_token %}
      <ul><li>{{ form.as_p }}</li></ul>

      <button type="submit">Preview your post</button>
    </form>
    
  </body>
</html>

games/templates/games/preview.html
{% load humanize %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>preview</title>
  </head>
  <body>
    
    <h1>Preview your submission</h1>

      <div>
        <p>Location: {{ form.data.location }}</p>
        <p>Game Date: {{ form.data.game_date|date:"l, F d, Y" }}</p>
        <p>Game Type: {{ form.data.get_game_display }}</p>
      </div>

      <div>
        <form action="{% url 'form_upload' %}" method="post">
          {% csrf_token %}
          {% for field in form %}
          {{ field.as_hidden }}
          {% endfor %}
          <input type="hidden" name="{{ stage_field }}" value="2" />
          <input type="hidden" name="{{ hash_field }}" value="{{ hash_value }}" />

          <!-- Submit button -->
          <button type="submit">Submit your post</button>
          <!-- Go back button -->
          <button type="submit">
            <a href="{% url 'form_upload' %}" 
              onClick="history.go(-1);return false;" >
              Go back and edit your post
            </a>
          </button>

          </div>

        </form>
      </div>
      


  </body>
</html>

games/templates/games/success.html
<h1>Success!</h1>

view_games/templates/view_games/game.html
{% load humanize %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>View game</title>
  </head>
  <body>
    
    <h1>Your game details</h1>

      <div>
        <p>Location: {{ game.location }}</p>
        <p>Game Date: {{ game.game_date|date:"l, F d, Y" }}</p>
        <p>Game Type: {{ game.get_game_display }}</p>
      </div>

  </body>
</html>

view_games/templates/view_games/index.html
{% if game_list %}

<p>Select a game</p>

<div>

  {% for game in game_list %}
    <a href="game/{{ game }}/">{{ game }}</a><br />
  {% endfor %}

</div>

{% else %}

  <div>
    <p>Oops! No games are available.</p>
  </div>

{% endif %}